// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtb_random_gemm.h for the primary calling header

#ifndef VERILATED_VTB_RANDOM_GEMM___024ROOT_H_
#define VERILATED_VTB_RANDOM_GEMM___024ROOT_H_  // guard

#include "verilated.h"
#include "verilated_timing.h"
class Vtb_random_gemm_systolic;
class Vtb_random_gemm_systolic_setup__D1_P10;
class Vtb_random_gemm_systolic_setup__P10;


class Vtb_random_gemm__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtb_random_gemm___024root final : public VerilatedModule {
  public:
    // CELLS
    Vtb_random_gemm_systolic_setup__P10* __PVT__tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__weight_data_setup;
    Vtb_random_gemm_systolic_setup__D1_P10* __PVT__tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__weight_valid_setup;
    Vtb_random_gemm_systolic_setup__P10* __PVT__tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__input_data_setup;
    Vtb_random_gemm_systolic_setup__D1_P10* __PVT__tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__input_valid_setup;
    Vtb_random_gemm_systolic* __PVT__tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__super_sys_instance__DOT__core0;
    Vtb_random_gemm_systolic* __PVT__tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__super_sys_instance__DOT__core1;
    Vtb_random_gemm_systolic* __PVT__tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__super_sys_instance__DOT__core2;
    Vtb_random_gemm_systolic* __PVT__tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__super_sys_instance__DOT__core3;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        CData/*0:0*/ tb_random_gemm__DOT__sel_for_test;
        VL_IN8(rst,0,0);
        CData/*0:0*/ tb_random_gemm__DOT__system_bus_en;
        CData/*0:0*/ tb_random_gemm__DOT__system_bus_rdwr;
        CData/*4:0*/ tb_random_gemm__DOT__interface_control;
        CData/*0:0*/ tb_random_gemm__DOT__interface_rdwr;
        CData/*0:0*/ tb_random_gemm__DOT__interface_en;
        VlWide<4>/*127:0*/ tb_random_gemm__DOT__interface_rd_data;
        VlWide<4>/*127:0*/ tb_random_gemm__DOT__test_interface_wr_data;
        CData/*4:0*/ tb_random_gemm__DOT__test_interface_control;
        CData/*0:0*/ tb_random_gemm__DOT__test_interface_en;
        CData/*0:0*/ tb_random_gemm__DOT__test_interface_rdwr;
        CData/*4:0*/ tb_random_gemm__DOT__selected_interface_control;
        CData/*0:0*/ tb_random_gemm__DOT__selected_interface_en;
        CData/*0:0*/ tb_random_gemm__DOT__selected_interface_rdwr;
        CData/*0:0*/ tb_random_gemm__DOT__last;
        CData/*0:0*/ tb_random_gemm__DOT__first;
        CData/*7:0*/ tb_random_gemm__DOT____Vlvbound_h848f6088__0;
        CData/*7:0*/ tb_random_gemm__DOT____Vlvbound_h16e23e8d__0;
        CData/*3:0*/ tb_random_gemm__DOT__DUT__DOT__buffer_empty;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__ready_for_HI;
        CData/*1:0*/ tb_random_gemm__DOT__DUT__DOT__mode;
        CData/*3:0*/ tb_random_gemm__DOT__DUT__DOT__rd_result;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__prefetch_done;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__if_mux_sel;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__w_mux_sel;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__if_en;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__wfetch;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__if_mux_sel_buffered;
        CData/*1:0*/ tb_random_gemm__DOT__DUT__DOT__buffer_sel;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__gen_addr_store;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__interface_en_store;
        CData/*4:0*/ tb_random_gemm__DOT__DUT__DOT__interface_control_store;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__interface_rdwr_store;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__w_mux_sel_buffered;
        CData/*4:0*/ tb_random_gemm__DOT__DUT__DOT____Vcellout__buffer_instance__dout;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__done_store;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__can_store;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__gen_addr;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__accum_start;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__prefetch_start;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__we_accum_ctrl;
        CData/*6:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__all_if_mux_sel;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__old_valid_Psum_15;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__valid;
        CData/*7:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__super_sys_instance__DOT__core2_wfetch;
        CData/*7:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__super_sys_instance__DOT__core2_if_en;
        CData/*7:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__super_sys_instance__DOT__core3_wfetch;
        QData/*63:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__super_sys_instance__DOT____Vcellinp__core2__wdata;
        QData/*63:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__super_sys_instance__DOT____Vcellinp__core2__if_data;
        QData/*63:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__super_sys_instance__DOT____Vcellinp__core3__wdata;
        CData/*6:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__pipeline_gen_instance__DOT__internal;
        SData/*10:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__pipeline_gen_instance2__DOT__internal;
        SData/*14:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__pipeline_gen_instance3__DOT__internal;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT____Vcellout__genblk1__BRA__0__KET____DOT__acum_buffer_instance__empty;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT____Vcellout__genblk1__BRA__1__KET____DOT__acum_buffer_instance__empty;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT____Vcellinp__genblk1__BRA__1__KET____DOT__acum_buffer_instance__valid;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT____Vcellout__genblk1__BRA__2__KET____DOT__acum_buffer_instance__empty;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT____Vcellinp__genblk1__BRA__2__KET____DOT__acum_buffer_instance__valid;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT____Vcellout__genblk1__BRA__3__KET____DOT__acum_buffer_instance__empty;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT____Vcellinp__genblk1__BRA__3__KET____DOT__acum_buffer_instance__valid;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT__genblk1__BRA__0__KET____DOT__acum_buffer_instance__DOT__rd_en_1;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT__genblk1__BRA__0__KET____DOT__acum_buffer_instance__DOT__empty_;
    };
    struct {
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT__genblk1__BRA__0__KET____DOT__acum_buffer_instance__DOT__accumulator__DOT__full;
        CData/*4:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT__genblk1__BRA__0__KET____DOT__acum_buffer_instance__DOT__accumulator__DOT__wptr;
        CData/*4:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT__genblk1__BRA__0__KET____DOT__acum_buffer_instance__DOT__accumulator__DOT__rptr;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT__genblk1__BRA__0__KET____DOT__acum_buffer_instance__DOT__buffer_instance__DOT__full;
        CData/*4:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT__genblk1__BRA__0__KET____DOT__acum_buffer_instance__DOT__buffer_instance__DOT__wptr;
        CData/*4:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT__genblk1__BRA__0__KET____DOT__acum_buffer_instance__DOT__buffer_instance__DOT__rptr;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT__genblk1__BRA__1__KET____DOT__acum_buffer_instance__DOT__rd_en_1;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT__genblk1__BRA__1__KET____DOT__acum_buffer_instance__DOT__empty_;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT__genblk1__BRA__1__KET____DOT__acum_buffer_instance__DOT__accumulator__DOT__full;
        CData/*4:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT__genblk1__BRA__1__KET____DOT__acum_buffer_instance__DOT__accumulator__DOT__wptr;
        CData/*4:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT__genblk1__BRA__1__KET____DOT__acum_buffer_instance__DOT__accumulator__DOT__rptr;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT__genblk1__BRA__1__KET____DOT__acum_buffer_instance__DOT__buffer_instance__DOT__full;
        CData/*4:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT__genblk1__BRA__1__KET____DOT__acum_buffer_instance__DOT__buffer_instance__DOT__wptr;
        CData/*4:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT__genblk1__BRA__1__KET____DOT__acum_buffer_instance__DOT__buffer_instance__DOT__rptr;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT__genblk1__BRA__2__KET____DOT__acum_buffer_instance__DOT__rd_en_1;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT__genblk1__BRA__2__KET____DOT__acum_buffer_instance__DOT__empty_;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT__genblk1__BRA__2__KET____DOT__acum_buffer_instance__DOT__accumulator__DOT__full;
        CData/*4:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT__genblk1__BRA__2__KET____DOT__acum_buffer_instance__DOT__accumulator__DOT__wptr;
        CData/*4:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT__genblk1__BRA__2__KET____DOT__acum_buffer_instance__DOT__accumulator__DOT__rptr;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT__genblk1__BRA__2__KET____DOT__acum_buffer_instance__DOT__buffer_instance__DOT__full;
        CData/*4:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT__genblk1__BRA__2__KET____DOT__acum_buffer_instance__DOT__buffer_instance__DOT__wptr;
        CData/*4:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT__genblk1__BRA__2__KET____DOT__acum_buffer_instance__DOT__buffer_instance__DOT__rptr;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT__genblk1__BRA__3__KET____DOT__acum_buffer_instance__DOT__rd_en_1;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT__genblk1__BRA__3__KET____DOT__acum_buffer_instance__DOT__empty_;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT__genblk1__BRA__3__KET____DOT__acum_buffer_instance__DOT__accumulator__DOT__full;
        CData/*4:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT__genblk1__BRA__3__KET____DOT__acum_buffer_instance__DOT__accumulator__DOT__wptr;
        CData/*4:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT__genblk1__BRA__3__KET____DOT__acum_buffer_instance__DOT__accumulator__DOT__rptr;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT__genblk1__BRA__3__KET____DOT__acum_buffer_instance__DOT__buffer_instance__DOT__full;
        CData/*4:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT__genblk1__BRA__3__KET____DOT__acum_buffer_instance__DOT__buffer_instance__DOT__wptr;
        CData/*4:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT__genblk1__BRA__3__KET____DOT__acum_buffer_instance__DOT__buffer_instance__DOT__rptr;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__buffer_instance__DOT__empty;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__buffer_instance__DOT__full;
        CData/*2:0*/ tb_random_gemm__DOT__DUT__DOT__buffer_instance__DOT__wptr;
        CData/*2:0*/ tb_random_gemm__DOT__DUT__DOT__buffer_instance__DOT__rptr;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__buffer_instance__DOT__rd_en_true;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__buffer_instance__DOT__cs;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__buffer_instance__DOT__ns;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__my_controller__DOT__conf_buff_read;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__my_controller__DOT__prefetch_done;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__my_controller__DOT__if_en;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__my_controller__DOT__wfetch;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__my_controller__DOT__clr_size_counter;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__my_controller__DOT__en_size_counter;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__my_controller__DOT__do_read_B;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__my_controller__DOT__do_read_A;
        CData/*2:0*/ tb_random_gemm__DOT__DUT__DOT__my_controller__DOT__ns;
        CData/*2:0*/ tb_random_gemm__DOT__DUT__DOT__my_controller__DOT__cs;
        CData/*2:0*/ tb_random_gemm__DOT__DUT__DOT__my_store_controller__DOT__cs;
        CData/*2:0*/ tb_random_gemm__DOT__DUT__DOT__my_store_controller__DOT__ns;
        CData/*4:0*/ tb_random_gemm__DOT__DUT__DOT__my_store_controller__DOT__count;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__my_store_controller__DOT__ovf;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__my_store_controller__DOT__count_en;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__my_store_controller__DOT__count_clr;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__memory_mapped_instance__DOT__tile_A_addr_wr_en;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__memory_mapped_instance__DOT__tile_A_buff_empty;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__memory_mapped_instance__DOT__tile_A_buff_full;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__memory_mapped_instance__DOT__tile_B_addr_wr_en;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__memory_mapped_instance__DOT__tile_B_buff_empty;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__memory_mapped_instance__DOT__tile_B_buff_full;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__memory_mapped_instance__DOT__tile_C_addr_wr_en;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__memory_mapped_instance__DOT__tile_C_buff_empty;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__memory_mapped_instance__DOT__tile_C_buff_full;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__memory_mapped_instance__DOT__tile_A_stride_wr_en;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__memory_mapped_instance__DOT__tile_A_stride_buff_empty;
    };
    struct {
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__memory_mapped_instance__DOT__tile_A_stride_buff_full;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__memory_mapped_instance__DOT__tile_B_stride_wr_en;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__memory_mapped_instance__DOT__tile_B_stride_buff_empty;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__memory_mapped_instance__DOT__tile_B_stride_buff_full;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__memory_mapped_instance__DOT__GEMM_control_wr_en;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__memory_mapped_instance__DOT__GEMM_control_buff_empty;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__memory_mapped_instance__DOT__GEMM_control_buff_full;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__memory_mapped_instance__DOT__tile_dimension_wr_en;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__memory_mapped_instance__DOT__tile_dimension_buff_empty;
        CData/*0:0*/ tb_random_gemm__DOT__DUT__DOT__memory_mapped_instance__DOT__tile_dimension_buff_full;
        CData/*1:0*/ tb_random_gemm__DOT__DUT__DOT__memory_mapped_instance__DOT__tileA_addr_buffer__DOT__wptr;
        CData/*1:0*/ tb_random_gemm__DOT__DUT__DOT__memory_mapped_instance__DOT__tileA_addr_buffer__DOT__rptr;
        CData/*1:0*/ tb_random_gemm__DOT__DUT__DOT__memory_mapped_instance__DOT__tileB_addr_buffer__DOT__wptr;
        CData/*1:0*/ tb_random_gemm__DOT__DUT__DOT__memory_mapped_instance__DOT__tileB_addr_buffer__DOT__rptr;
        CData/*1:0*/ tb_random_gemm__DOT__DUT__DOT__memory_mapped_instance__DOT__tileC_addr_buffer__DOT__wptr;
        CData/*1:0*/ tb_random_gemm__DOT__DUT__DOT__memory_mapped_instance__DOT__tileC_addr_buffer__DOT__rptr;
        CData/*1:0*/ tb_random_gemm__DOT__DUT__DOT__memory_mapped_instance__DOT__tileA_stride_buffer__DOT__wptr;
        CData/*1:0*/ tb_random_gemm__DOT__DUT__DOT__memory_mapped_instance__DOT__tileA_stride_buffer__DOT__rptr;
        CData/*1:0*/ tb_random_gemm__DOT__DUT__DOT__memory_mapped_instance__DOT__tileB_stride_buffer__DOT__wptr;
        CData/*1:0*/ tb_random_gemm__DOT__DUT__DOT__memory_mapped_instance__DOT__tileB_stride_buffer__DOT__rptr;
        CData/*1:0*/ tb_random_gemm__DOT__DUT__DOT__memory_mapped_instance__DOT__GEMM_control_buffer__DOT__wptr;
        CData/*1:0*/ tb_random_gemm__DOT__DUT__DOT__memory_mapped_instance__DOT__GEMM_control_buffer__DOT__rptr;
        CData/*1:0*/ tb_random_gemm__DOT__DUT__DOT__memory_mapped_instance__DOT__tile_dimension_buffer__DOT__wptr;
        CData/*1:0*/ tb_random_gemm__DOT__DUT__DOT__memory_mapped_instance__DOT__tile_dimension_buffer__DOT__rptr;
        CData/*0:0*/ tb_random_gemm__DOT__memory_instance__DOT__system_bus_en;
        CData/*0:0*/ tb_random_gemm__DOT__memory_instance__DOT__system_bus_rdwr;
        CData/*3:0*/ tb_random_gemm__DOT__memory_instance__DOT__system_bus_mask;
        IData/*31:0*/ tb_random_gemm__DOT__memory_instance__DOT__system_bus_wr_data;
        CData/*3:0*/ tb_random_gemm__DOT__memory_instance__DOT__interface_addr_ppl;
        CData/*3:0*/ tb_random_gemm__DOT__memory_instance__DOT__system_bus_addr_ppl;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_random_gemm__DOT__sel_for_test__0;
        CData/*0:0*/ __VactContinue;
        SData/*14:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__all_w_mux_sel;
        SData/*13:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__all_store;
        SData/*13:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__all_overwrite;
        SData/*15:0*/ tb_random_gemm__DOT__memory_instance__DOT__mask;
        SData/*15:0*/ tb_random_gemm__DOT__memory_instance__DOT__mask_ppl;
        SData/*15:0*/ tb_random_gemm__DOT__memory_instance__DOT__bank_wea;
        SData/*15:0*/ tb_random_gemm__DOT__memory_instance__DOT__bank_enb;
        SData/*15:0*/ tb_random_gemm__DOT__memory_instance__DOT__bank_web;
        SData/*15:0*/ tb_random_gemm__DOT__memory_instance__DOT__bank_web_;
        IData/*31:0*/ tb_random_gemm__DOT__system_bus_rd_data;
        IData/*31:0*/ tb_random_gemm__DOT__system_bus_wr_data;
        IData/*31:0*/ tb_random_gemm__DOT__system_bus_addr;
        VlWide<4>/*127:0*/ tb_random_gemm__DOT____Vcellout__DUT__interface_wr_data;
        IData/*31:0*/ tb_random_gemm__DOT__test_interface_addr;
        IData/*31:0*/ tb_random_gemm__DOT__selected_interface_addr;
        VlWide<4>/*127:0*/ tb_random_gemm__DOT__selected_interface_wr_data;
        IData/*31:0*/ tb_random_gemm__DOT__n;
        IData/*31:0*/ tb_random_gemm__DOT__m;
        IData/*31:0*/ tb_random_gemm__DOT__k;
        IData/*31:0*/ tb_random_gemm__DOT__i;
        IData/*31:0*/ tb_random_gemm__DOT__j;
        IData/*31:0*/ tb_random_gemm__DOT__M;
        IData/*31:0*/ tb_random_gemm__DOT__K;
        IData/*31:0*/ tb_random_gemm__DOT__N;
        IData/*31:0*/ tb_random_gemm__DOT__nsize;
        IData/*31:0*/ tb_random_gemm__DOT__msize;
        IData/*31:0*/ tb_random_gemm__DOT__ksize;
        IData/*31:0*/ tb_random_gemm__DOT__Tile_A_Address;
        IData/*31:0*/ tb_random_gemm__DOT__Tile_B_Address;
        IData/*31:0*/ tb_random_gemm__DOT__Tile_C_Address;
        IData/*31:0*/ tb_random_gemm__DOT__A_addr;
    };
    struct {
        IData/*31:0*/ tb_random_gemm__DOT__B_addr;
        IData/*31:0*/ tb_random_gemm__DOT__C_addr;
        IData/*31:0*/ tb_random_gemm__DOT__file_handle;
        IData/*31:0*/ tb_random_gemm__DOT__old_sel_for_test;
        IData/*31:0*/ tb_random_gemm__DOT__cycles_count;
        IData/*31:0*/ tb_random_gemm__DOT__count_rows_compared;
        IData/*31:0*/ tb_random_gemm__DOT__total_tiles;
        IData/*31:0*/ tb_random_gemm__DOT__n_;
        IData/*31:0*/ tb_random_gemm__DOT__nsize_;
        IData/*31:0*/ tb_random_gemm__DOT__msize_;
        IData/*31:0*/ tb_random_gemm__DOT__N_;
        IData/*31:0*/ tb_random_gemm__DOT__unnamedblk1__DOT__test_no;
        IData/*31:0*/ tb_random_gemm__DOT__unnamedblk1__DOT__unnamedblk2__DOT__i;
        IData/*31:0*/ tb_random_gemm__DOT__unnamedblk1__DOT__unnamedblk2__DOT__unnamedblk3__DOT__j;
        IData/*31:0*/ tb_random_gemm__DOT__unnamedblk1__DOT__unnamedblk4__DOT__i;
        IData/*31:0*/ tb_random_gemm__DOT__unnamedblk1__DOT__unnamedblk4__DOT__unnamedblk5__DOT__j;
        IData/*31:0*/ tb_random_gemm__DOT__unnamedblk1__DOT__unnamedblk6__DOT__l;
        IData/*31:0*/ tb_random_gemm__DOT__unnamedblk1__DOT__unnamedblk7__DOT__l;
        IData/*31:0*/ tb_random_gemm__DOT__unnamedblk8__DOT__i;
        IData/*31:0*/ tb_random_gemm__DOT____Vlvbound_hda49e2e8__0;
        IData/*31:0*/ tb_random_gemm__DOT____Vlvbound_hda49e2e8__1;
        IData/*31:0*/ tb_random_gemm__DOT__DUT__DOT__tile_B_addr;
        IData/*31:0*/ tb_random_gemm__DOT__DUT__DOT__tile_B_stride;
        IData/*31:0*/ tb_random_gemm__DOT__DUT__DOT__next_addr_store;
        IData/*31:0*/ tb_random_gemm__DOT__DUT__DOT__current_addr;
        IData/*31:0*/ tb_random_gemm__DOT__DUT__DOT__next_addr;
        IData/*31:0*/ tb_random_gemm__DOT__DUT__DOT__next_row_addr_store;
        IData/*31:0*/ tb_random_gemm__DOT__DUT__DOT__current_store_addr;
        IData/*16:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__valid_Psum;
        VlWide<6>/*191:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__super_sys_instance__DOT____Vcellinp__core2__bias;
        VlWide<6>/*191:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__super_sys_instance__DOT____Vcellinp__core3__bias;
        VlWide<4>/*127:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT____Vcellout__genblk1__BRA__0__KET____DOT__acum_buffer_instance__o_data;
        VlWide<4>/*127:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT____Vcellout__genblk1__BRA__1__KET____DOT__acum_buffer_instance__o_data;
        VlWide<4>/*127:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT____Vcellout__genblk1__BRA__2__KET____DOT__acum_buffer_instance__o_data;
        VlWide<4>/*127:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT____Vcellout__genblk1__BRA__3__KET____DOT__acum_buffer_instance__o_data;
        VlWide<4>/*127:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT__genblk1__BRA__0__KET____DOT__acum_buffer_instance__DOT__din_1;
        VlWide<4>/*127:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT__genblk1__BRA__0__KET____DOT__acum_buffer_instance__DOT__dout_1;
        VlWide<4>/*127:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT__genblk1__BRA__1__KET____DOT__acum_buffer_instance__DOT__din_1;
        VlWide<4>/*127:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT__genblk1__BRA__1__KET____DOT__acum_buffer_instance__DOT__dout_1;
        VlWide<4>/*127:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT__genblk1__BRA__2__KET____DOT__acum_buffer_instance__DOT__din_1;
        VlWide<4>/*127:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT__genblk1__BRA__2__KET____DOT__acum_buffer_instance__DOT__dout_1;
        VlWide<4>/*127:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT__genblk1__BRA__3__KET____DOT__acum_buffer_instance__DOT__din_1;
        VlWide<4>/*127:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT__genblk1__BRA__3__KET____DOT__acum_buffer_instance__DOT__dout_1;
        VlWide<3>/*71:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__genblk1__BRA__0__KET____DOT__of_data_setup_inst__DOT__genblk1__BRA__0__KET____DOT__pipeline_gen_instance__DOT__internal;
        QData/*47:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__genblk1__BRA__0__KET____DOT__of_data_setup_inst__DOT__genblk1__BRA__1__KET____DOT__pipeline_gen_instance__DOT__internal;
        IData/*23:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__genblk1__BRA__0__KET____DOT__of_data_setup_inst__DOT__genblk1__BRA__2__KET____DOT__pipeline_gen_instance__DOT__internal;
        VlWide<3>/*71:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__genblk1__BRA__4__KET____DOT__of_data_setup_inst__DOT__genblk1__BRA__0__KET____DOT__pipeline_gen_instance__DOT__internal;
        QData/*47:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__genblk1__BRA__4__KET____DOT__of_data_setup_inst__DOT__genblk1__BRA__1__KET____DOT__pipeline_gen_instance__DOT__internal;
        IData/*23:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__genblk1__BRA__4__KET____DOT__of_data_setup_inst__DOT__genblk1__BRA__2__KET____DOT__pipeline_gen_instance__DOT__internal;
        VlWide<3>/*71:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__genblk1__BRA__8__KET____DOT__of_data_setup_inst__DOT__genblk1__BRA__0__KET____DOT__pipeline_gen_instance__DOT__internal;
        QData/*47:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__genblk1__BRA__8__KET____DOT__of_data_setup_inst__DOT__genblk1__BRA__1__KET____DOT__pipeline_gen_instance__DOT__internal;
        IData/*23:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__genblk1__BRA__8__KET____DOT__of_data_setup_inst__DOT__genblk1__BRA__2__KET____DOT__pipeline_gen_instance__DOT__internal;
        VlWide<3>/*71:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__genblk1__BRA__12__KET____DOT__of_data_setup_inst__DOT__genblk1__BRA__0__KET____DOT__pipeline_gen_instance__DOT__internal;
        QData/*47:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__genblk1__BRA__12__KET____DOT__of_data_setup_inst__DOT__genblk1__BRA__1__KET____DOT__pipeline_gen_instance__DOT__internal;
        IData/*23:0*/ tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__genblk1__BRA__12__KET____DOT__of_data_setup_inst__DOT__genblk1__BRA__2__KET____DOT__pipeline_gen_instance__DOT__internal;
        IData/*31:0*/ tb_random_gemm__DOT__DUT__DOT__my_controller__DOT__count;
        IData/*31:0*/ tb_random_gemm__DOT__DUT__DOT__memory_mapped_instance__DOT__GEMM_control;
        IData/*31:0*/ tb_random_gemm__DOT__DUT__DOT__memory_mapped_instance__DOT__tile_dimension;
        IData/*31:0*/ tb_random_gemm__DOT__memory_instance__DOT__system_bus_addr;
        IData/*31:0*/ __VstlIterCount;
        IData/*31:0*/ __VactIterCount;
        VlUnpacked<VlWide<18>/*559:0*/, 70> tb_random_gemm__DOT__A;
        VlUnpacked<VlWide<18>/*559:0*/, 70> tb_random_gemm__DOT__B;
        VlUnpacked<VlWide<70>/*2239:0*/, 70> tb_random_gemm__DOT__C;
    };
    struct {
        VlUnpacked<VlWide<4>/*127:0*/, 16> tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT__genblk1__BRA__0__KET____DOT__acum_buffer_instance__DOT__accumulator__DOT__fifo;
        VlUnpacked<VlWide<4>/*127:0*/, 16> tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT__genblk1__BRA__0__KET____DOT__acum_buffer_instance__DOT__buffer_instance__DOT__fifo;
        VlUnpacked<VlWide<4>/*127:0*/, 16> tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT__genblk1__BRA__1__KET____DOT__acum_buffer_instance__DOT__accumulator__DOT__fifo;
        VlUnpacked<VlWide<4>/*127:0*/, 16> tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT__genblk1__BRA__1__KET____DOT__acum_buffer_instance__DOT__buffer_instance__DOT__fifo;
        VlUnpacked<VlWide<4>/*127:0*/, 16> tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT__genblk1__BRA__2__KET____DOT__acum_buffer_instance__DOT__accumulator__DOT__fifo;
        VlUnpacked<VlWide<4>/*127:0*/, 16> tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT__genblk1__BRA__2__KET____DOT__acum_buffer_instance__DOT__buffer_instance__DOT__fifo;
        VlUnpacked<VlWide<4>/*127:0*/, 16> tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT__genblk1__BRA__3__KET____DOT__acum_buffer_instance__DOT__accumulator__DOT__fifo;
        VlUnpacked<VlWide<4>/*127:0*/, 16> tb_random_gemm__DOT__DUT__DOT__datapath_instance__DOT__accumulator_instance__DOT__genblk1__BRA__3__KET____DOT__acum_buffer_instance__DOT__buffer_instance__DOT__fifo;
        VlUnpacked<CData/*4:0*/, 4> tb_random_gemm__DOT__DUT__DOT__buffer_instance__DOT__fifo;
        VlUnpacked<IData/*31:0*/, 2> tb_random_gemm__DOT__DUT__DOT__memory_mapped_instance__DOT__tileA_addr_buffer__DOT__fifo;
        VlUnpacked<IData/*31:0*/, 2> tb_random_gemm__DOT__DUT__DOT__memory_mapped_instance__DOT__tileB_addr_buffer__DOT__fifo;
        VlUnpacked<IData/*31:0*/, 2> tb_random_gemm__DOT__DUT__DOT__memory_mapped_instance__DOT__tileC_addr_buffer__DOT__fifo;
        VlUnpacked<IData/*31:0*/, 2> tb_random_gemm__DOT__DUT__DOT__memory_mapped_instance__DOT__tileA_stride_buffer__DOT__fifo;
        VlUnpacked<IData/*31:0*/, 2> tb_random_gemm__DOT__DUT__DOT__memory_mapped_instance__DOT__tileB_stride_buffer__DOT__fifo;
        VlUnpacked<IData/*31:0*/, 2> tb_random_gemm__DOT__DUT__DOT__memory_mapped_instance__DOT__GEMM_control_buffer__DOT__fifo;
        VlUnpacked<IData/*31:0*/, 2> tb_random_gemm__DOT__DUT__DOT__memory_mapped_instance__DOT__tile_dimension_buffer__DOT__fifo;
        VlUnpacked<CData/*7:0*/, 16> tb_random_gemm__DOT__memory_instance__DOT__bank_dina;
        VlUnpacked<CData/*7:0*/, 16> tb_random_gemm__DOT__memory_instance__DOT__bank_douta;
        VlUnpacked<SData/*9:0*/, 16> tb_random_gemm__DOT__memory_instance__DOT__bank_addra;
        VlUnpacked<CData/*7:0*/, 16> tb_random_gemm__DOT__memory_instance__DOT__bank_doutb;
        VlUnpacked<SData/*9:0*/, 16> tb_random_gemm__DOT__memory_instance__DOT__bank_addrb;
        VlUnpacked<CData/*7:0*/, 16> tb_random_gemm__DOT__memory_instance__DOT__bank_dinb;
        VlUnpacked<CData/*7:0*/, 16> tb_random_gemm__DOT__memory_instance__DOT__bank_dinb_;
        VlUnpacked<VlUnpacked<CData/*7:0*/, 1024>, 16> tb_random_gemm__DOT__memory_instance__DOT__mem;
        VlUnpacked<CData/*0:0*/, 6> __Vm_traceActivity;
    };
    VlTriggerScheduler __VtrigSched_h21418e1f__0;
    VlTriggerScheduler __VtrigSched_h7b1b7f80__0;
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<2> __VactTriggered;
    VlTriggerVec<2> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vtb_random_gemm__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vtb_random_gemm___024root(Vtb_random_gemm__Syms* symsp, const char* v__name);
    ~Vtb_random_gemm___024root();
    VL_UNCOPYABLE(Vtb_random_gemm___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
