// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtb_random_gemm.h for the primary calling header

#ifndef VERILATED_VTB_RANDOM_GEMM_SYSTOLIC_H_
#define VERILATED_VTB_RANDOM_GEMM_SYSTOLIC_H_  // guard

#include "verilated.h"
#include "verilated_timing.h"


class Vtb_random_gemm__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtb_random_gemm_systolic final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(rst,0,0);
        VL_IN8(if_en,7,0);
        VL_IN8(wfetch,7,0);
        VL_IN8(wfetch_halt,7,0);
        VL_IN64(if_data,63,0);
        VL_IN64(wdata,63,0);
        VL_OUT64(if_data_out,63,0);
        VL_OUT8(if_en_out,7,0);
        VL_OUT8(wfetch_out,7,0);
        VL_OUT64(wdata_out,63,0);
        VlWide<14>/*447:0*/ __PVT__A_data;
        QData/*55:0*/ __PVT__A_ready;
        VlWide<14>/*447:0*/ __PVT__W_data;
        QData/*55:0*/ __PVT__W_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__0__KET____DOT__genblk1__BRA__0__KET____DOT__genblk1__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__0__KET____DOT__genblk1__BRA__0__KET____DOT__genblk1__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__0__KET____DOT__genblk1__BRA__0__KET____DOT__genblk1__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__0__KET____DOT__genblk1__BRA__0__KET____DOT__genblk1__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__0__KET____DOT__genblk1__BRA__0__KET____DOT__genblk1__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__0__KET____DOT__genblk1__BRA__1__KET____DOT__genblk1__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__0__KET____DOT__genblk1__BRA__1__KET____DOT__genblk1__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__0__KET____DOT__genblk1__BRA__1__KET____DOT__genblk1__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__0__KET____DOT__genblk1__BRA__1__KET____DOT__genblk1__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__0__KET____DOT__genblk1__BRA__1__KET____DOT__genblk1__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__0__KET____DOT__genblk1__BRA__2__KET____DOT__genblk1__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__0__KET____DOT__genblk1__BRA__2__KET____DOT__genblk1__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__0__KET____DOT__genblk1__BRA__2__KET____DOT__genblk1__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__0__KET____DOT__genblk1__BRA__2__KET____DOT__genblk1__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__0__KET____DOT__genblk1__BRA__2__KET____DOT__genblk1__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__0__KET____DOT__genblk1__BRA__3__KET____DOT__genblk1__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__0__KET____DOT__genblk1__BRA__3__KET____DOT__genblk1__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__0__KET____DOT__genblk1__BRA__3__KET____DOT__genblk1__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__0__KET____DOT__genblk1__BRA__3__KET____DOT__genblk1__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__0__KET____DOT__genblk1__BRA__3__KET____DOT__genblk1__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__0__KET____DOT__genblk1__BRA__4__KET____DOT__genblk1__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__0__KET____DOT__genblk1__BRA__4__KET____DOT__genblk1__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__0__KET____DOT__genblk1__BRA__4__KET____DOT__genblk1__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__0__KET____DOT__genblk1__BRA__4__KET____DOT__genblk1__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__0__KET____DOT__genblk1__BRA__4__KET____DOT__genblk1__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__0__KET____DOT__genblk1__BRA__5__KET____DOT__genblk1__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__0__KET____DOT__genblk1__BRA__5__KET____DOT__genblk1__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__0__KET____DOT__genblk1__BRA__5__KET____DOT__genblk1__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__0__KET____DOT__genblk1__BRA__5__KET____DOT__genblk1__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__0__KET____DOT__genblk1__BRA__5__KET____DOT__genblk1__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__0__KET____DOT__genblk1__BRA__6__KET____DOT__genblk1__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__0__KET____DOT__genblk1__BRA__6__KET____DOT__genblk1__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__0__KET____DOT__genblk1__BRA__6__KET____DOT__genblk1__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__0__KET____DOT__genblk1__BRA__6__KET____DOT__genblk1__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__0__KET____DOT__genblk1__BRA__6__KET____DOT__genblk1__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__0__KET____DOT__genblk1__BRA__7__KET____DOT__genblk1__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__0__KET____DOT__genblk1__BRA__7__KET____DOT__genblk1__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__0__KET____DOT__genblk1__BRA__7__KET____DOT__genblk1__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__0__KET____DOT__genblk1__BRA__7__KET____DOT__genblk1__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__0__KET____DOT__genblk1__BRA__7__KET____DOT__genblk1__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__1__KET____DOT__genblk1__BRA__0__KET____DOT__genblk3__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__1__KET____DOT__genblk1__BRA__0__KET____DOT__genblk3__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__1__KET____DOT__genblk1__BRA__0__KET____DOT__genblk3__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__1__KET____DOT__genblk1__BRA__0__KET____DOT__genblk3__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__1__KET____DOT__genblk1__BRA__0__KET____DOT__genblk3__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__1__KET____DOT__genblk1__BRA__1__KET____DOT__genblk3__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__1__KET____DOT__genblk1__BRA__1__KET____DOT__genblk3__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__1__KET____DOT__genblk1__BRA__1__KET____DOT__genblk3__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__1__KET____DOT__genblk1__BRA__1__KET____DOT__genblk3__DOT__mac_instance__A_out;
    };
    struct {
        CData/*0:0*/ __Vcellout__genblk1__BRA__1__KET____DOT__genblk1__BRA__1__KET____DOT__genblk3__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__1__KET____DOT__genblk1__BRA__2__KET____DOT__genblk3__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__1__KET____DOT__genblk1__BRA__2__KET____DOT__genblk3__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__1__KET____DOT__genblk1__BRA__2__KET____DOT__genblk3__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__1__KET____DOT__genblk1__BRA__2__KET____DOT__genblk3__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__1__KET____DOT__genblk1__BRA__2__KET____DOT__genblk3__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__1__KET____DOT__genblk1__BRA__3__KET____DOT__genblk3__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__1__KET____DOT__genblk1__BRA__3__KET____DOT__genblk3__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__1__KET____DOT__genblk1__BRA__3__KET____DOT__genblk3__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__1__KET____DOT__genblk1__BRA__3__KET____DOT__genblk3__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__1__KET____DOT__genblk1__BRA__3__KET____DOT__genblk3__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__1__KET____DOT__genblk1__BRA__4__KET____DOT__genblk3__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__1__KET____DOT__genblk1__BRA__4__KET____DOT__genblk3__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__1__KET____DOT__genblk1__BRA__4__KET____DOT__genblk3__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__1__KET____DOT__genblk1__BRA__4__KET____DOT__genblk3__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__1__KET____DOT__genblk1__BRA__4__KET____DOT__genblk3__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__1__KET____DOT__genblk1__BRA__5__KET____DOT__genblk3__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__1__KET____DOT__genblk1__BRA__5__KET____DOT__genblk3__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__1__KET____DOT__genblk1__BRA__5__KET____DOT__genblk3__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__1__KET____DOT__genblk1__BRA__5__KET____DOT__genblk3__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__1__KET____DOT__genblk1__BRA__5__KET____DOT__genblk3__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__1__KET____DOT__genblk1__BRA__6__KET____DOT__genblk3__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__1__KET____DOT__genblk1__BRA__6__KET____DOT__genblk3__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__1__KET____DOT__genblk1__BRA__6__KET____DOT__genblk3__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__1__KET____DOT__genblk1__BRA__6__KET____DOT__genblk3__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__1__KET____DOT__genblk1__BRA__6__KET____DOT__genblk3__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__1__KET____DOT__genblk1__BRA__7__KET____DOT__genblk3__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__1__KET____DOT__genblk1__BRA__7__KET____DOT__genblk3__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__1__KET____DOT__genblk1__BRA__7__KET____DOT__genblk3__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__1__KET____DOT__genblk1__BRA__7__KET____DOT__genblk3__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__1__KET____DOT__genblk1__BRA__7__KET____DOT__genblk3__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__2__KET____DOT__genblk1__BRA__0__KET____DOT__genblk3__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__2__KET____DOT__genblk1__BRA__0__KET____DOT__genblk3__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__2__KET____DOT__genblk1__BRA__0__KET____DOT__genblk3__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__2__KET____DOT__genblk1__BRA__0__KET____DOT__genblk3__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__2__KET____DOT__genblk1__BRA__0__KET____DOT__genblk3__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__2__KET____DOT__genblk1__BRA__1__KET____DOT__genblk3__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__2__KET____DOT__genblk1__BRA__1__KET____DOT__genblk3__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__2__KET____DOT__genblk1__BRA__1__KET____DOT__genblk3__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__2__KET____DOT__genblk1__BRA__1__KET____DOT__genblk3__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__2__KET____DOT__genblk1__BRA__1__KET____DOT__genblk3__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__2__KET____DOT__genblk1__BRA__2__KET____DOT__genblk3__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__2__KET____DOT__genblk1__BRA__2__KET____DOT__genblk3__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__2__KET____DOT__genblk1__BRA__2__KET____DOT__genblk3__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__2__KET____DOT__genblk1__BRA__2__KET____DOT__genblk3__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__2__KET____DOT__genblk1__BRA__2__KET____DOT__genblk3__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__2__KET____DOT__genblk1__BRA__3__KET____DOT__genblk3__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__2__KET____DOT__genblk1__BRA__3__KET____DOT__genblk3__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__2__KET____DOT__genblk1__BRA__3__KET____DOT__genblk3__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__2__KET____DOT__genblk1__BRA__3__KET____DOT__genblk3__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__2__KET____DOT__genblk1__BRA__3__KET____DOT__genblk3__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__2__KET____DOT__genblk1__BRA__4__KET____DOT__genblk3__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__2__KET____DOT__genblk1__BRA__4__KET____DOT__genblk3__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__2__KET____DOT__genblk1__BRA__4__KET____DOT__genblk3__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__2__KET____DOT__genblk1__BRA__4__KET____DOT__genblk3__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__2__KET____DOT__genblk1__BRA__4__KET____DOT__genblk3__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__2__KET____DOT__genblk1__BRA__5__KET____DOT__genblk3__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__2__KET____DOT__genblk1__BRA__5__KET____DOT__genblk3__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__2__KET____DOT__genblk1__BRA__5__KET____DOT__genblk3__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__2__KET____DOT__genblk1__BRA__5__KET____DOT__genblk3__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__2__KET____DOT__genblk1__BRA__5__KET____DOT__genblk3__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__2__KET____DOT__genblk1__BRA__6__KET____DOT__genblk3__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__2__KET____DOT__genblk1__BRA__6__KET____DOT__genblk3__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__2__KET____DOT__genblk1__BRA__6__KET____DOT__genblk3__DOT__mac_instance__W_en;
    };
    struct {
        CData/*7:0*/ __Vcellout__genblk1__BRA__2__KET____DOT__genblk1__BRA__6__KET____DOT__genblk3__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__2__KET____DOT__genblk1__BRA__6__KET____DOT__genblk3__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__2__KET____DOT__genblk1__BRA__7__KET____DOT__genblk3__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__2__KET____DOT__genblk1__BRA__7__KET____DOT__genblk3__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__2__KET____DOT__genblk1__BRA__7__KET____DOT__genblk3__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__2__KET____DOT__genblk1__BRA__7__KET____DOT__genblk3__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__2__KET____DOT__genblk1__BRA__7__KET____DOT__genblk3__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__3__KET____DOT__genblk1__BRA__0__KET____DOT__genblk3__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__3__KET____DOT__genblk1__BRA__0__KET____DOT__genblk3__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__3__KET____DOT__genblk1__BRA__0__KET____DOT__genblk3__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__3__KET____DOT__genblk1__BRA__0__KET____DOT__genblk3__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__3__KET____DOT__genblk1__BRA__0__KET____DOT__genblk3__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__3__KET____DOT__genblk1__BRA__1__KET____DOT__genblk3__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__3__KET____DOT__genblk1__BRA__1__KET____DOT__genblk3__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__3__KET____DOT__genblk1__BRA__1__KET____DOT__genblk3__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__3__KET____DOT__genblk1__BRA__1__KET____DOT__genblk3__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__3__KET____DOT__genblk1__BRA__1__KET____DOT__genblk3__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__3__KET____DOT__genblk1__BRA__2__KET____DOT__genblk3__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__3__KET____DOT__genblk1__BRA__2__KET____DOT__genblk3__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__3__KET____DOT__genblk1__BRA__2__KET____DOT__genblk3__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__3__KET____DOT__genblk1__BRA__2__KET____DOT__genblk3__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__3__KET____DOT__genblk1__BRA__2__KET____DOT__genblk3__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__3__KET____DOT__genblk1__BRA__3__KET____DOT__genblk3__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__3__KET____DOT__genblk1__BRA__3__KET____DOT__genblk3__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__3__KET____DOT__genblk1__BRA__3__KET____DOT__genblk3__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__3__KET____DOT__genblk1__BRA__3__KET____DOT__genblk3__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__3__KET____DOT__genblk1__BRA__3__KET____DOT__genblk3__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__3__KET____DOT__genblk1__BRA__4__KET____DOT__genblk3__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__3__KET____DOT__genblk1__BRA__4__KET____DOT__genblk3__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__3__KET____DOT__genblk1__BRA__4__KET____DOT__genblk3__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__3__KET____DOT__genblk1__BRA__4__KET____DOT__genblk3__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__3__KET____DOT__genblk1__BRA__4__KET____DOT__genblk3__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__3__KET____DOT__genblk1__BRA__5__KET____DOT__genblk3__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__3__KET____DOT__genblk1__BRA__5__KET____DOT__genblk3__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__3__KET____DOT__genblk1__BRA__5__KET____DOT__genblk3__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__3__KET____DOT__genblk1__BRA__5__KET____DOT__genblk3__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__3__KET____DOT__genblk1__BRA__5__KET____DOT__genblk3__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__3__KET____DOT__genblk1__BRA__6__KET____DOT__genblk3__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__3__KET____DOT__genblk1__BRA__6__KET____DOT__genblk3__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__3__KET____DOT__genblk1__BRA__6__KET____DOT__genblk3__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__3__KET____DOT__genblk1__BRA__6__KET____DOT__genblk3__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__3__KET____DOT__genblk1__BRA__6__KET____DOT__genblk3__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__3__KET____DOT__genblk1__BRA__7__KET____DOT__genblk3__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__3__KET____DOT__genblk1__BRA__7__KET____DOT__genblk3__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__3__KET____DOT__genblk1__BRA__7__KET____DOT__genblk3__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__3__KET____DOT__genblk1__BRA__7__KET____DOT__genblk3__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__3__KET____DOT__genblk1__BRA__7__KET____DOT__genblk3__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__4__KET____DOT__genblk1__BRA__0__KET____DOT__genblk3__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__4__KET____DOT__genblk1__BRA__0__KET____DOT__genblk3__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__4__KET____DOT__genblk1__BRA__0__KET____DOT__genblk3__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__4__KET____DOT__genblk1__BRA__0__KET____DOT__genblk3__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__4__KET____DOT__genblk1__BRA__0__KET____DOT__genblk3__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__4__KET____DOT__genblk1__BRA__1__KET____DOT__genblk3__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__4__KET____DOT__genblk1__BRA__1__KET____DOT__genblk3__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__4__KET____DOT__genblk1__BRA__1__KET____DOT__genblk3__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__4__KET____DOT__genblk1__BRA__1__KET____DOT__genblk3__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__4__KET____DOT__genblk1__BRA__1__KET____DOT__genblk3__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__4__KET____DOT__genblk1__BRA__2__KET____DOT__genblk3__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__4__KET____DOT__genblk1__BRA__2__KET____DOT__genblk3__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__4__KET____DOT__genblk1__BRA__2__KET____DOT__genblk3__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__4__KET____DOT__genblk1__BRA__2__KET____DOT__genblk3__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__4__KET____DOT__genblk1__BRA__2__KET____DOT__genblk3__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__4__KET____DOT__genblk1__BRA__3__KET____DOT__genblk3__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__4__KET____DOT__genblk1__BRA__3__KET____DOT__genblk3__DOT__mac_instance__W_ready;
    };
    struct {
        CData/*0:0*/ __Vcellinp__genblk1__BRA__4__KET____DOT__genblk1__BRA__3__KET____DOT__genblk3__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__4__KET____DOT__genblk1__BRA__3__KET____DOT__genblk3__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__4__KET____DOT__genblk1__BRA__3__KET____DOT__genblk3__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__4__KET____DOT__genblk1__BRA__4__KET____DOT__genblk3__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__4__KET____DOT__genblk1__BRA__4__KET____DOT__genblk3__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__4__KET____DOT__genblk1__BRA__4__KET____DOT__genblk3__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__4__KET____DOT__genblk1__BRA__4__KET____DOT__genblk3__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__4__KET____DOT__genblk1__BRA__4__KET____DOT__genblk3__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__4__KET____DOT__genblk1__BRA__5__KET____DOT__genblk3__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__4__KET____DOT__genblk1__BRA__5__KET____DOT__genblk3__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__4__KET____DOT__genblk1__BRA__5__KET____DOT__genblk3__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__4__KET____DOT__genblk1__BRA__5__KET____DOT__genblk3__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__4__KET____DOT__genblk1__BRA__5__KET____DOT__genblk3__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__4__KET____DOT__genblk1__BRA__6__KET____DOT__genblk3__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__4__KET____DOT__genblk1__BRA__6__KET____DOT__genblk3__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__4__KET____DOT__genblk1__BRA__6__KET____DOT__genblk3__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__4__KET____DOT__genblk1__BRA__6__KET____DOT__genblk3__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__4__KET____DOT__genblk1__BRA__6__KET____DOT__genblk3__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__4__KET____DOT__genblk1__BRA__7__KET____DOT__genblk3__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__4__KET____DOT__genblk1__BRA__7__KET____DOT__genblk3__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__4__KET____DOT__genblk1__BRA__7__KET____DOT__genblk3__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__4__KET____DOT__genblk1__BRA__7__KET____DOT__genblk3__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__4__KET____DOT__genblk1__BRA__7__KET____DOT__genblk3__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__5__KET____DOT__genblk1__BRA__0__KET____DOT__genblk3__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__5__KET____DOT__genblk1__BRA__0__KET____DOT__genblk3__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__5__KET____DOT__genblk1__BRA__0__KET____DOT__genblk3__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__5__KET____DOT__genblk1__BRA__0__KET____DOT__genblk3__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__5__KET____DOT__genblk1__BRA__0__KET____DOT__genblk3__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__5__KET____DOT__genblk1__BRA__1__KET____DOT__genblk3__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__5__KET____DOT__genblk1__BRA__1__KET____DOT__genblk3__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__5__KET____DOT__genblk1__BRA__1__KET____DOT__genblk3__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__5__KET____DOT__genblk1__BRA__1__KET____DOT__genblk3__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__5__KET____DOT__genblk1__BRA__1__KET____DOT__genblk3__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__5__KET____DOT__genblk1__BRA__2__KET____DOT__genblk3__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__5__KET____DOT__genblk1__BRA__2__KET____DOT__genblk3__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__5__KET____DOT__genblk1__BRA__2__KET____DOT__genblk3__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__5__KET____DOT__genblk1__BRA__2__KET____DOT__genblk3__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__5__KET____DOT__genblk1__BRA__2__KET____DOT__genblk3__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__5__KET____DOT__genblk1__BRA__3__KET____DOT__genblk3__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__5__KET____DOT__genblk1__BRA__3__KET____DOT__genblk3__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__5__KET____DOT__genblk1__BRA__3__KET____DOT__genblk3__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__5__KET____DOT__genblk1__BRA__3__KET____DOT__genblk3__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__5__KET____DOT__genblk1__BRA__3__KET____DOT__genblk3__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__5__KET____DOT__genblk1__BRA__4__KET____DOT__genblk3__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__5__KET____DOT__genblk1__BRA__4__KET____DOT__genblk3__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__5__KET____DOT__genblk1__BRA__4__KET____DOT__genblk3__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__5__KET____DOT__genblk1__BRA__4__KET____DOT__genblk3__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__5__KET____DOT__genblk1__BRA__4__KET____DOT__genblk3__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__5__KET____DOT__genblk1__BRA__5__KET____DOT__genblk3__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__5__KET____DOT__genblk1__BRA__5__KET____DOT__genblk3__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__5__KET____DOT__genblk1__BRA__5__KET____DOT__genblk3__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__5__KET____DOT__genblk1__BRA__5__KET____DOT__genblk3__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__5__KET____DOT__genblk1__BRA__5__KET____DOT__genblk3__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__5__KET____DOT__genblk1__BRA__6__KET____DOT__genblk3__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__5__KET____DOT__genblk1__BRA__6__KET____DOT__genblk3__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__5__KET____DOT__genblk1__BRA__6__KET____DOT__genblk3__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__5__KET____DOT__genblk1__BRA__6__KET____DOT__genblk3__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__5__KET____DOT__genblk1__BRA__6__KET____DOT__genblk3__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__5__KET____DOT__genblk1__BRA__7__KET____DOT__genblk3__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__5__KET____DOT__genblk1__BRA__7__KET____DOT__genblk3__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__5__KET____DOT__genblk1__BRA__7__KET____DOT__genblk3__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__5__KET____DOT__genblk1__BRA__7__KET____DOT__genblk3__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__5__KET____DOT__genblk1__BRA__7__KET____DOT__genblk3__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__6__KET____DOT__genblk1__BRA__0__KET____DOT__genblk3__DOT__mac_instance__W_out;
    };
    struct {
        CData/*0:0*/ __Vcellout__genblk1__BRA__6__KET____DOT__genblk1__BRA__0__KET____DOT__genblk3__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__6__KET____DOT__genblk1__BRA__0__KET____DOT__genblk3__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__6__KET____DOT__genblk1__BRA__0__KET____DOT__genblk3__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__6__KET____DOT__genblk1__BRA__0__KET____DOT__genblk3__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__6__KET____DOT__genblk1__BRA__1__KET____DOT__genblk3__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__6__KET____DOT__genblk1__BRA__1__KET____DOT__genblk3__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__6__KET____DOT__genblk1__BRA__1__KET____DOT__genblk3__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__6__KET____DOT__genblk1__BRA__1__KET____DOT__genblk3__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__6__KET____DOT__genblk1__BRA__1__KET____DOT__genblk3__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__6__KET____DOT__genblk1__BRA__2__KET____DOT__genblk3__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__6__KET____DOT__genblk1__BRA__2__KET____DOT__genblk3__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__6__KET____DOT__genblk1__BRA__2__KET____DOT__genblk3__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__6__KET____DOT__genblk1__BRA__2__KET____DOT__genblk3__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__6__KET____DOT__genblk1__BRA__2__KET____DOT__genblk3__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__6__KET____DOT__genblk1__BRA__3__KET____DOT__genblk3__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__6__KET____DOT__genblk1__BRA__3__KET____DOT__genblk3__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__6__KET____DOT__genblk1__BRA__3__KET____DOT__genblk3__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__6__KET____DOT__genblk1__BRA__3__KET____DOT__genblk3__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__6__KET____DOT__genblk1__BRA__3__KET____DOT__genblk3__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__6__KET____DOT__genblk1__BRA__4__KET____DOT__genblk3__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__6__KET____DOT__genblk1__BRA__4__KET____DOT__genblk3__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__6__KET____DOT__genblk1__BRA__4__KET____DOT__genblk3__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__6__KET____DOT__genblk1__BRA__4__KET____DOT__genblk3__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__6__KET____DOT__genblk1__BRA__4__KET____DOT__genblk3__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__6__KET____DOT__genblk1__BRA__5__KET____DOT__genblk3__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__6__KET____DOT__genblk1__BRA__5__KET____DOT__genblk3__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__6__KET____DOT__genblk1__BRA__5__KET____DOT__genblk3__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__6__KET____DOT__genblk1__BRA__5__KET____DOT__genblk3__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__6__KET____DOT__genblk1__BRA__5__KET____DOT__genblk3__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__6__KET____DOT__genblk1__BRA__6__KET____DOT__genblk3__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__6__KET____DOT__genblk1__BRA__6__KET____DOT__genblk3__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__6__KET____DOT__genblk1__BRA__6__KET____DOT__genblk3__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__6__KET____DOT__genblk1__BRA__6__KET____DOT__genblk3__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__6__KET____DOT__genblk1__BRA__6__KET____DOT__genblk3__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__6__KET____DOT__genblk1__BRA__7__KET____DOT__genblk3__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__6__KET____DOT__genblk1__BRA__7__KET____DOT__genblk3__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__6__KET____DOT__genblk1__BRA__7__KET____DOT__genblk3__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__6__KET____DOT__genblk1__BRA__7__KET____DOT__genblk3__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__6__KET____DOT__genblk1__BRA__7__KET____DOT__genblk3__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__7__KET____DOT__genblk1__BRA__0__KET____DOT__genblk2__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__7__KET____DOT__genblk1__BRA__0__KET____DOT__genblk2__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__7__KET____DOT__genblk1__BRA__0__KET____DOT__genblk2__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__7__KET____DOT__genblk1__BRA__0__KET____DOT__genblk2__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__7__KET____DOT__genblk1__BRA__0__KET____DOT__genblk2__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__7__KET____DOT__genblk1__BRA__1__KET____DOT__genblk2__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__7__KET____DOT__genblk1__BRA__1__KET____DOT__genblk2__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__7__KET____DOT__genblk1__BRA__1__KET____DOT__genblk2__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__7__KET____DOT__genblk1__BRA__1__KET____DOT__genblk2__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__7__KET____DOT__genblk1__BRA__1__KET____DOT__genblk2__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__7__KET____DOT__genblk1__BRA__2__KET____DOT__genblk2__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__7__KET____DOT__genblk1__BRA__2__KET____DOT__genblk2__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__7__KET____DOT__genblk1__BRA__2__KET____DOT__genblk2__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__7__KET____DOT__genblk1__BRA__2__KET____DOT__genblk2__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__7__KET____DOT__genblk1__BRA__2__KET____DOT__genblk2__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__7__KET____DOT__genblk1__BRA__3__KET____DOT__genblk2__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__7__KET____DOT__genblk1__BRA__3__KET____DOT__genblk2__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__7__KET____DOT__genblk1__BRA__3__KET____DOT__genblk2__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__7__KET____DOT__genblk1__BRA__3__KET____DOT__genblk2__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__7__KET____DOT__genblk1__BRA__3__KET____DOT__genblk2__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__7__KET____DOT__genblk1__BRA__4__KET____DOT__genblk2__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__7__KET____DOT__genblk1__BRA__4__KET____DOT__genblk2__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__7__KET____DOT__genblk1__BRA__4__KET____DOT__genblk2__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__7__KET____DOT__genblk1__BRA__4__KET____DOT__genblk2__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__7__KET____DOT__genblk1__BRA__4__KET____DOT__genblk2__DOT__mac_instance__A_ready;
    };
    struct {
        CData/*7:0*/ __Vcellout__genblk1__BRA__7__KET____DOT__genblk1__BRA__5__KET____DOT__genblk2__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__7__KET____DOT__genblk1__BRA__5__KET____DOT__genblk2__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__7__KET____DOT__genblk1__BRA__5__KET____DOT__genblk2__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__7__KET____DOT__genblk1__BRA__5__KET____DOT__genblk2__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__7__KET____DOT__genblk1__BRA__5__KET____DOT__genblk2__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__7__KET____DOT__genblk1__BRA__6__KET____DOT__genblk2__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__7__KET____DOT__genblk1__BRA__6__KET____DOT__genblk2__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__7__KET____DOT__genblk1__BRA__6__KET____DOT__genblk2__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__7__KET____DOT__genblk1__BRA__6__KET____DOT__genblk2__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__7__KET____DOT__genblk1__BRA__6__KET____DOT__genblk2__DOT__mac_instance__A_ready;
        CData/*7:0*/ __Vcellout__genblk1__BRA__7__KET____DOT__genblk1__BRA__7__KET____DOT__genblk2__DOT__mac_instance__W_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__7__KET____DOT__genblk1__BRA__7__KET____DOT__genblk2__DOT__mac_instance__W_ready;
        CData/*0:0*/ __Vcellinp__genblk1__BRA__7__KET____DOT__genblk1__BRA__7__KET____DOT__genblk2__DOT__mac_instance__W_en;
        CData/*7:0*/ __Vcellout__genblk1__BRA__7__KET____DOT__genblk1__BRA__7__KET____DOT__genblk2__DOT__mac_instance__A_out;
        CData/*0:0*/ __Vcellout__genblk1__BRA__7__KET____DOT__genblk1__BRA__7__KET____DOT__genblk2__DOT__mac_instance__A_ready;
        VL_INW(bias,191,0,6);
        VL_OUTW(of_data,191,0,6);
        VlWide<42>/*1343:0*/ __PVT__P_data;
        IData/*23:0*/ __Vcellout__genblk1__BRA__0__KET____DOT__genblk1__BRA__0__KET____DOT__genblk1__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__0__KET____DOT__genblk1__BRA__1__KET____DOT__genblk1__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__0__KET____DOT__genblk1__BRA__2__KET____DOT__genblk1__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__0__KET____DOT__genblk1__BRA__3__KET____DOT__genblk1__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__0__KET____DOT__genblk1__BRA__4__KET____DOT__genblk1__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__0__KET____DOT__genblk1__BRA__5__KET____DOT__genblk1__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__0__KET____DOT__genblk1__BRA__6__KET____DOT__genblk1__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__0__KET____DOT__genblk1__BRA__7__KET____DOT__genblk1__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__1__KET____DOT__genblk1__BRA__0__KET____DOT__genblk3__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__1__KET____DOT__genblk1__BRA__1__KET____DOT__genblk3__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__1__KET____DOT__genblk1__BRA__2__KET____DOT__genblk3__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__1__KET____DOT__genblk1__BRA__3__KET____DOT__genblk3__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__1__KET____DOT__genblk1__BRA__4__KET____DOT__genblk3__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__1__KET____DOT__genblk1__BRA__5__KET____DOT__genblk3__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__1__KET____DOT__genblk1__BRA__6__KET____DOT__genblk3__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__1__KET____DOT__genblk1__BRA__7__KET____DOT__genblk3__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__2__KET____DOT__genblk1__BRA__0__KET____DOT__genblk3__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__2__KET____DOT__genblk1__BRA__1__KET____DOT__genblk3__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__2__KET____DOT__genblk1__BRA__2__KET____DOT__genblk3__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__2__KET____DOT__genblk1__BRA__3__KET____DOT__genblk3__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__2__KET____DOT__genblk1__BRA__4__KET____DOT__genblk3__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__2__KET____DOT__genblk1__BRA__5__KET____DOT__genblk3__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__2__KET____DOT__genblk1__BRA__6__KET____DOT__genblk3__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__2__KET____DOT__genblk1__BRA__7__KET____DOT__genblk3__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__3__KET____DOT__genblk1__BRA__0__KET____DOT__genblk3__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__3__KET____DOT__genblk1__BRA__1__KET____DOT__genblk3__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__3__KET____DOT__genblk1__BRA__2__KET____DOT__genblk3__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__3__KET____DOT__genblk1__BRA__3__KET____DOT__genblk3__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__3__KET____DOT__genblk1__BRA__4__KET____DOT__genblk3__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__3__KET____DOT__genblk1__BRA__5__KET____DOT__genblk3__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__3__KET____DOT__genblk1__BRA__6__KET____DOT__genblk3__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__3__KET____DOT__genblk1__BRA__7__KET____DOT__genblk3__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__4__KET____DOT__genblk1__BRA__0__KET____DOT__genblk3__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__4__KET____DOT__genblk1__BRA__1__KET____DOT__genblk3__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__4__KET____DOT__genblk1__BRA__2__KET____DOT__genblk3__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__4__KET____DOT__genblk1__BRA__3__KET____DOT__genblk3__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__4__KET____DOT__genblk1__BRA__4__KET____DOT__genblk3__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__4__KET____DOT__genblk1__BRA__5__KET____DOT__genblk3__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__4__KET____DOT__genblk1__BRA__6__KET____DOT__genblk3__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__4__KET____DOT__genblk1__BRA__7__KET____DOT__genblk3__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__5__KET____DOT__genblk1__BRA__0__KET____DOT__genblk3__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__5__KET____DOT__genblk1__BRA__1__KET____DOT__genblk3__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__5__KET____DOT__genblk1__BRA__2__KET____DOT__genblk3__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__5__KET____DOT__genblk1__BRA__3__KET____DOT__genblk3__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__5__KET____DOT__genblk1__BRA__4__KET____DOT__genblk3__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__5__KET____DOT__genblk1__BRA__5__KET____DOT__genblk3__DOT__mac_instance__P_out;
    };
    struct {
        IData/*23:0*/ __Vcellout__genblk1__BRA__5__KET____DOT__genblk1__BRA__6__KET____DOT__genblk3__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__5__KET____DOT__genblk1__BRA__7__KET____DOT__genblk3__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__6__KET____DOT__genblk1__BRA__0__KET____DOT__genblk3__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__6__KET____DOT__genblk1__BRA__1__KET____DOT__genblk3__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__6__KET____DOT__genblk1__BRA__2__KET____DOT__genblk3__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__6__KET____DOT__genblk1__BRA__3__KET____DOT__genblk3__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__6__KET____DOT__genblk1__BRA__4__KET____DOT__genblk3__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__6__KET____DOT__genblk1__BRA__5__KET____DOT__genblk3__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__6__KET____DOT__genblk1__BRA__6__KET____DOT__genblk3__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__6__KET____DOT__genblk1__BRA__7__KET____DOT__genblk3__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__7__KET____DOT__genblk1__BRA__0__KET____DOT__genblk2__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__7__KET____DOT__genblk1__BRA__1__KET____DOT__genblk2__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__7__KET____DOT__genblk1__BRA__2__KET____DOT__genblk2__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__7__KET____DOT__genblk1__BRA__3__KET____DOT__genblk2__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__7__KET____DOT__genblk1__BRA__4__KET____DOT__genblk2__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__7__KET____DOT__genblk1__BRA__5__KET____DOT__genblk2__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__7__KET____DOT__genblk1__BRA__6__KET____DOT__genblk2__DOT__mac_instance__P_out;
        IData/*23:0*/ __Vcellout__genblk1__BRA__7__KET____DOT__genblk1__BRA__7__KET____DOT__genblk2__DOT__mac_instance__P_out;
    };

    // INTERNAL VARIABLES
    Vtb_random_gemm__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vtb_random_gemm_systolic(Vtb_random_gemm__Syms* symsp, const char* v__name);
    ~Vtb_random_gemm_systolic();
    VL_UNCOPYABLE(Vtb_random_gemm_systolic);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
