# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-32452-ddrc-user1/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a100tcsg324-1

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include /home/abdul_waheed/Music/FYP/rtl/Script/build {
      /home/abdul_waheed/Music/FYP/rtl/Common/Config.sv
      /home/abdul_waheed/Music/FYP/rtl/RISCV_Core/Datapath/ALU.sv
      /home/abdul_waheed/Music/FYP/rtl/RISCV_Core/Datapath/Branch_block.sv
      /home/abdul_waheed/Music/FYP/rtl/RISCV_Core/Datapath/CSR_reg.sv
      /home/abdul_waheed/Music/FYP/rtl/RISCV_Core/Decoders/Controller.sv
      /home/abdul_waheed/Music/FYP/rtl/RISCV_Core/Datapath/Decode.sv
      /home/abdul_waheed/Music/FYP/rtl/RISCV_Core/Datapath/Fetch.sv
      /home/abdul_waheed/Music/FYP/rtl/RISCV_Core/Datapath/Hazard_detection.sv
      /home/abdul_waheed/Music/FYP/rtl/RISCV_Core/Datapath/Instrmem.sv
      /home/abdul_waheed/Music/FYP/rtl/RISCV_Core/Decoders/LS_controller.sv
      /home/abdul_waheed/Music/FYP/rtl/Controller/Load_Ex_controller.sv
      /home/abdul_waheed/Music/FYP/rtl/RISCV_Core/Utilities/Pipeline_reg.sv
      /home/abdul_waheed/Music/FYP/rtl/RISCV_Core/RISC_V.sv
      /home/abdul_waheed/Music/FYP/rtl/RISCV_Core/Utilities/Regfile.sv
      /home/abdul_waheed/Music/FYP/rtl/RISCV_Core/Decoders/Rocc_controller.sv
      /home/abdul_waheed/Music/FYP/rtl/Controller/Store_Controller.sv
      /home/abdul_waheed/Music/FYP/rtl/Datapath/accumulator.sv
      /home/abdul_waheed/Music/FYP/rtl/Datapath/acum_buffer.sv
      /home/abdul_waheed/Music/FYP/rtl/Utilities/buffer.sv
      /home/abdul_waheed/Music/FYP/rtl/RISCV_Core/Datapath/datapath.sv
      /home/abdul_waheed/Music/FYP/rtl/gemm.sv
      /home/abdul_waheed/Music/FYP/rtl/Datapath/gemm_datapath.sv
      /home/abdul_waheed/Music/FYP/rtl/Datapath/gemm_decoder.sv
      /home/abdul_waheed/Music/FYP/rtl/Datapath/mac.sv
      /home/abdul_waheed/Music/FYP/rtl/Datapath/memory.sv
      /home/abdul_waheed/Music/FYP/rtl/Datapath/memory_mapped.sv
      /home/abdul_waheed/Music/FYP/rtl/RISCV_Core/Utilities/mux16x1.sv
      /home/abdul_waheed/Music/FYP/rtl/Utilities/muxes.sv
      /home/abdul_waheed/Music/FYP/rtl/Datapath/pipeline_gen.sv
      /home/abdul_waheed/Music/FYP/rtl/Datapath/super_sys.sv
      /home/abdul_waheed/Music/FYP/rtl/Datapath/systolic_setup_reverse.sv
      /home/abdul_waheed/Music/FYP/rtl/Datapath/systolic_setup.sv
      /home/abdul_waheed/Music/FYP/rtl/Datapath/systolic.sv
      /home/abdul_waheed/Music/FYP/rtl/RISCV_Core/Utilities/timer.sv
      /home/abdul_waheed/Music/FYP/rtl/RISCV_Core/Datapath/wb_stage.sv
      /home/abdul_waheed/Music/FYP/rtl/top.sv
      /home/abdul_waheed/Music/FYP/rtl/RISCV_Core/Utilities/anodecontroller.sv
      /home/abdul_waheed/Music/FYP/rtl/RISCV_Core/Utilities/sevenseg.sv
      /home/abdul_waheed/Music/FYP/rtl/RISCV_Core/Utilities/x7segb8.sv
      /home/abdul_waheed/Music/FYP/rtl/RISCV_Core/Datapath/refreshcounter.sv
      /home/abdul_waheed/Music/FYP/rtl/Controller/buffer_accum_ctrl.sv
      /home/abdul_waheed/Music/FYP/rtl/top_gemm.sv
      /home/abdul_waheed/Music/FYP/rtl/RISCV_Core/CEP.sv
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top top
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-32452-ddrc-user1/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
